channels:
  - conda-forge
  - defaults
dependencies:
  - openjdk
  - maven
  - make
  - cmake
  - xtensor-zarr=0.0.3=*_1
  - xtensor != 0.23.5
  - openimageio
  - zlib
  - blosc
  - nodejs
  - z5py >= 2.0.8
  - python == 3.7.9
  - scikit-image
  - pytest
  - zarr >= 2.8.0
  - pip
  - pandas
  - tabulate
  - pip:
      - pyn5
      - git+https://github.com/grlee77/zarrita.git@codec_update
