---
name: Build

on: [push, pull_request]

jobs:
  test:
    name: ${{ matrix.platform }} ${{ matrix.python-version }}
    runs-on: ${{ matrix.platform }}

    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest]
        python-version: [3.7]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v1
        with:
          auto-update-conda: true
          channels: conda-forge,ome
          environment-file: environment.yml
          python-version: ${{ matrix.python-version }}
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run tests
        shell: bash -l {0}
        run: make
