---
name: Build with Zarr dev

on: [push, pull_request]

jobs:
  test:
    name: ${{ matrix.platform }} ${{ matrix.python-version }}
    runs-on: ${{ matrix.platform }}

    strategy:
      fail-fast: true
      matrix:
        platform: [ubuntu-latest]
        python-version: [3.7]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          channels: conda-forge,ome
          environment-file: environment.yml
          python-version: ${{ matrix.python-version }}
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true

      - name: Install zarr dev
        shell: bash -l {0}
        run: |
          python -m pip install git+https://github.com/zarr-developers/zarr-python.git@master

      - name: Run tests
        shell: bash -l {0}
        run: make

      - name: Generate Report
        shell: bash -l {0}
        run: |
            python test/test_read_all.py

      - name: Archive HTML test report
        uses: actions/upload-artifact@v2
        with:
          name: test-report-html
          path: report.html

      - name: Archive Markdown test report
        uses: actions/upload-artifact@v2
        with:
          name: test-report-md
          path: report.md
